name: Movie search app cypress test

on: [push]

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'search tests - electron'
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 120
          browser: electron
          spec: cypress/e2e/movie-search.tests.cy.js
