name: Movie search app cypress test

on: [push]

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with: 
          install: true
          node-version: '16'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          install: true
          config-file: ./cypress.config.js
          wait-on: 'http://[::1]:8080'
          browser: electron
          spec: cypress/e2e/movie_search_tests.cy.js
          
